# Generated by Django 6.1 on 2026-08-24 15:02

import django.core.validators
import django.db.models.deletion
import portfolios.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('activities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='دفتر العلوم الذكي', max_length=200, verbose_name='عنوان الدفتر')),
                ('introduction', models.TextField(blank=True, verbose_name='نبذة الطالبة')),
                ('learning_goals', models.TextField(blank=True, verbose_name='أهداف التعلم')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='portfolios/covers/', verbose_name='صورة الغلاف')),
                ('is_active', models.BooleanField(default=True, verbose_name='دفتر نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='academics.academicyear', verbose_name='العام الدراسي')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='academics.classroom', verbose_name='الشعبة')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL, verbose_name='الطالبة')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='academics.subject', verbose_name='المقرر')),
            ],
            options={
                'verbose_name': 'دفتر طالبة',
                'verbose_name_plural': 'دفاتر الطالبات',
                'ordering': ['student__first_name'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان القسم')),
                ('description', models.TextField(blank=True, verbose_name='وصف القسم')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='الترتيب')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='portfolios.portfolio', verbose_name='الدفتر')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_sections', to='academics.unit', verbose_name='الوحدة')),
            ],
            options={
                'verbose_name': 'قسم دفتر',
                'verbose_name_plural': 'أقسام الدفاتر',
                'ordering': ['portfolio', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان العمل')),
                ('description', models.TextField(blank=True, verbose_name='وصف العمل')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('submitted', 'تم التسليم'), ('under_review', 'قيد التقييم'), ('revision_required', 'يحتاج تعديلًا'), ('resubmitted', 'أعيد التسليم'), ('approved', 'تم الاعتماد'), ('featured', 'عمل متميز')], db_index=True, default='draft', max_length=30, verbose_name='حالة العمل')),
                ('is_featured', models.BooleanField(default=False, verbose_name='عمل متميز')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ آخر تسليم')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='activities.activity', verbose_name='النشاط المرتبط')),
                ('collaborators', models.ManyToManyField(blank=True, limit_choices_to={'role': 'student'}, related_name='collaborative_submissions', to=settings.AUTH_USER_MODEL, verbose_name='الطالبات المشاركات')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='portfolios.portfolio', verbose_name='دفتر الطالبة')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='portfolios.portfoliosection', verbose_name='قسم الدفتر')),
            ],
            options={
                'verbose_name': 'عمل طالبة',
                'verbose_name_plural': 'أعمال الطالبات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='التعليق')),
                ('is_private', models.BooleanField(default=False, verbose_name='تعليق خاص بالمعلمة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التعليق')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_comments', to=settings.AUTH_USER_MODEL, verbose_name='كاتب التعليق')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='portfolios.submission', verbose_name='العمل')),
            ],
            options={
                'verbose_name': 'تعليق على عمل',
                'verbose_name_plural': 'تعليقات الأعمال',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(default=1, verbose_name='رقم النسخة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات الطالبة')),
                ('reflection', models.TextField(blank=True, help_text='ماذا تعلمت الطالبة؟ وما الذي ستطوره؟', verbose_name='التأمل الذاتي')),
                ('ai_used', models.BooleanField(default=False, verbose_name='تم استخدام الذكاء الاصطناعي')),
                ('ai_tools', models.CharField(blank=True, max_length=255, verbose_name='أدوات الذكاء الاصطناعي المستخدمة')),
                ('ai_usage_description', models.TextField(blank=True, verbose_name='وصف استخدام الذكاء الاصطناعي')),
                ('is_current', models.BooleanField(default=True, verbose_name='النسخة الحالية')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ رفع النسخة')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='portfolios.submission', verbose_name='العمل')),
            ],
            options={
                'verbose_name': 'نسخة عمل',
                'verbose_name_plural': 'نسخ الأعمال',
                'ordering': ['submission', '-version_number'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='portfolios/submissions/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'ppt', 'pptx', 'xls', 'xlsx', 'jpg', 'jpeg', 'png', 'webp', 'mp4', 'mov', 'webm', 'mp3', 'wav', 'm4a']), portfolios.models.validate_portfolio_file_size], verbose_name='الملف')),
                ('media_type', models.CharField(choices=[('document', 'مستند'), ('image', 'صورة'), ('video', 'فيديو'), ('audio', 'تسجيل صوتي'), ('presentation', 'عرض تقديمي'), ('other', 'ملف آخر')], default='document', max_length=20, verbose_name='نوع الملف')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='وصف الملف')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='اسم الملف الأصلي')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='نوع محتوى الملف')),
                ('size_bytes', models.PositiveBigIntegerField(default=0, verbose_name='حجم الملف بالبايت')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='portfolios.submissionversion', verbose_name='نسخة العمل')),
            ],
            options={
                'verbose_name': 'مرفق',
                'verbose_name_plural': 'المرفقات',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='portfolio',
            constraint=models.UniqueConstraint(fields=('student', 'classroom', 'subject', 'academic_year'), name='unique_student_portfolio'),
        ),
        migrations.AddConstraint(
            model_name='portfoliosection',
            constraint=models.UniqueConstraint(fields=('portfolio', 'order'), name='unique_portfolio_section_order'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(condition=models.Q(('activity__isnull', False)), fields=('portfolio', 'activity'), name='unique_portfolio_activity_submission'),
        ),
        migrations.AddConstraint(
            model_name='submissionversion',
            constraint=models.UniqueConstraint(fields=('submission', 'version_number'), name='unique_submission_version'),
        ),
    ]
