services:
  - type: web
    name: scince-web
    runtime: python
    plan: free
    region: frankfurt
    branch: main
    buildCommand: ./build.sh
    startCommand: gunicorn scince.wsgi:application
    healthCheckPath: /
    autoDeployTrigger: commit
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: scince-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: 3.13.7

databases:
  - name: scince-db
    plan: free
    region: frankfurt
    databaseName: scince
    user: scince
