# Generated by Django 6.1 on 2026-08-24 15:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('activities', '0001_initial'),
        ('portfolios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم الشارة')),
                ('description', models.TextField(blank=True, verbose_name='وصف الشارة')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='assessment/badges/', verbose_name='أيقونة الشارة')),
                ('color', models.CharField(default='#C59D4F', max_length=20, verbose_name='لون الشارة')),
                ('is_active', models.BooleanField(default=True, verbose_name='شارة نشطة')),
            ],
            options={
                'verbose_name': 'شارة',
                'verbose_name_plural': 'الشارات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='اسم سلم التقدير')),
                ('description', models.TextField(blank=True, verbose_name='وصف سلم التقدير')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('created_by', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.PROTECT, related_name='created_rubrics', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubrics', to='academics.subject', verbose_name='المقرر')),
            ],
            options={
                'verbose_name': 'سلم تقدير',
                'verbose_name_plural': 'سلالم التقدير',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الدرجة الكلية')),
                ('general_feedback', models.TextField(blank=True, verbose_name='التغذية الراجعة')),
                ('audio_feedback', models.FileField(blank=True, null=True, upload_to='assessment/audio_feedback/', verbose_name='تغذية راجعة صوتية')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('published', 'تم نشر التقييم'), ('revision_required', 'يحتاج تعديلًا')], db_index=True, default='draft', max_length=30, verbose_name='حالة التقييم')),
                ('evaluated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التقييم')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ نشر التقييم')),
                ('evaluator', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to=settings.AUTH_USER_MODEL, verbose_name='المقيّمة')),
                ('submission_version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='portfolios.submissionversion', verbose_name='نسخة العمل')),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='assessment.rubric', verbose_name='سلم التقدير')),
            ],
            options={
                'verbose_name': 'تقييم',
                'verbose_name_plural': 'التقييمات',
                'ordering': ['-evaluated_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityRubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الربط')),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rubric_assignment', to='activities.activity', verbose_name='النشاط')),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rubric_assignments', to=settings.AUTH_USER_MODEL, verbose_name='تم الربط بواسطة')),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity_assignments', to='assessment.rubric', verbose_name='سلم التقدير')),
            ],
            options={
                'verbose_name': 'ربط نشاط بسلم تقدير',
                'verbose_name_plural': 'ربط الأنشطة بسلالم التقدير',
            },
        ),
        migrations.CreateModel(
            name='RubricCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان المعيار')),
                ('description', models.TextField(blank=True, verbose_name='وصف المعيار')),
                ('max_points', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الدرجة القصوى')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='الترتيب')),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='assessment.rubric', verbose_name='سلم التقدير')),
            ],
            options={
                'verbose_name': 'معيار تقييم',
                'verbose_name_plural': 'معايير التقييم',
                'ordering': ['rubric', 'order'],
            },
        ),
        migrations.CreateModel(
            name='CriterionScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الدرجة')),
                ('feedback', models.TextField(blank=True, verbose_name='ملاحظة المعيار')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterion_scores', to='assessment.evaluation', verbose_name='التقييم')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scores', to='assessment.rubriccriterion', verbose_name='المعيار')),
            ],
            options={
                'verbose_name': 'درجة معيار',
                'verbose_name_plural': 'درجات المعايير',
            },
        ),
        migrations.CreateModel(
            name='StudentBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, verbose_name='سبب منح الشارة')),
                ('awarded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ المنح')),
                ('awarded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='awarded_badges', to=settings.AUTH_USER_MODEL, verbose_name='منحت بواسطة')),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='assessment.badge', verbose_name='الشارة')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_badges', to='portfolios.portfolio', verbose_name='دفتر الطالبة')),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awarded_badges', to='portfolios.submission', verbose_name='العمل المرتبط')),
            ],
            options={
                'verbose_name': 'شارة طالبة',
                'verbose_name_plural': 'شارات الطالبات',
                'ordering': ['-awarded_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='rubriccriterion',
            constraint=models.UniqueConstraint(fields=('rubric', 'order'), name='unique_rubric_criterion_order'),
        ),
        migrations.AddConstraint(
            model_name='criterionscore',
            constraint=models.UniqueConstraint(fields=('evaluation', 'criterion'), name='unique_evaluation_criterion_score'),
        ),
        migrations.AddConstraint(
            model_name='studentbadge',
            constraint=models.UniqueConstraint(fields=('portfolio', 'badge', 'submission'), name='unique_portfolio_badge_submission'),
        ),
    ]
