# Generated by Django 6.1 on 2026-08-24 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان النشاط')),
                ('description', models.TextField(blank=True, verbose_name='وصف النشاط')),
                ('instructions', models.TextField(verbose_name='تعليمات التنفيذ')),
                ('activity_type', models.CharField(choices=[('worksheet', 'ورقة عمل'), ('foldable', 'مطوية'), ('experiment', 'تجربة علمية'), ('project', 'مشروع'), ('report', 'تقرير'), ('presentation', 'عرض تقديمي'), ('infographic', 'إنفوجرافيك'), ('concept_map', 'خريطة مفاهيم'), ('image', 'تصميم أو صورة'), ('video', 'فيديو'), ('audio', 'تسجيل صوتي'), ('ai_work', 'عمل بالذكاء الاصطناعي'), ('other', 'عمل آخر')], db_index=True, default='worksheet', max_length=30, verbose_name='نوع النشاط')),
                ('work_mode', models.CharField(choices=[('individual', 'فردي'), ('group', 'جماعي')], default='individual', max_length=20, verbose_name='طريقة التنفيذ')),
                ('ai_policy', models.CharField(choices=[('not_allowed', 'غير مسموح'), ('optional', 'مسموح اختياريًا'), ('required', 'مطلوب'), ('disclosure_required', 'مسموح مع توضيح الاستخدام')], default='disclosure_required', max_length=30, verbose_name='سياسة استخدام الذكاء الاصطناعي')),
                ('max_score', models.DecimalField(decimal_places=2, default=10, max_digits=6, verbose_name='الدرجة النهائية')),
                ('opens_at', models.DateTimeField(blank=True, null=True, verbose_name='بداية استقبال الأعمال')),
                ('due_at', models.DateTimeField(blank=True, null=True, verbose_name='موعد التسليم')),
                ('allow_late_submission', models.BooleanField(default=True, verbose_name='السماح بالتسليم المتأخر')),
                ('allowed_extensions', models.JSONField(blank=True, default=list, help_text='مثال: pdf, jpg, png, mp4', verbose_name='امتدادات الملفات المسموحة')),
                ('max_files', models.PositiveSmallIntegerField(default=5, verbose_name='الحد الأعلى لعدد الملفات')),
                ('max_file_size_mb', models.PositiveIntegerField(default=100, verbose_name='الحد الأعلى لحجم الملف بالميجابايت')),
                ('reference_file', models.FileField(blank=True, null=True, upload_to='activities/references/', verbose_name='ملف إرشادي')),
                ('is_published', models.BooleanField(db_index=True, default=False, verbose_name='منشور للطالبات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('created_by', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.PROTECT, related_name='created_activities', to=settings.AUTH_USER_MODEL, verbose_name='المعلمة')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='academics.lesson', verbose_name='الدرس')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='academics.subject', verbose_name='المقرر')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='academics.term', verbose_name='الفصل الدراسي')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='academics.unit', verbose_name='الوحدة')),
            ],
            options={
                'verbose_name': 'نشاط',
                'verbose_name_plural': 'الأنشطة',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإسناد')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_assignments', to='activities.activity', verbose_name='النشاط')),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_activities', to=settings.AUTH_USER_MODEL, verbose_name='تم الإسناد بواسطة')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_assignments', to='academics.classroom', verbose_name='الشعبة')),
            ],
            options={
                'verbose_name': 'إسناد نشاط',
                'verbose_name_plural': 'إسنادات الأنشطة',
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='classrooms',
            field=models.ManyToManyField(related_name='activities', through='activities.ActivityAssignment', to='academics.classroom', verbose_name='الشعب المستهدفة'),
        ),
        migrations.AddConstraint(
            model_name='activityassignment',
            constraint=models.UniqueConstraint(fields=('activity', 'classroom'), name='unique_activity_classroom'),
        ),
    ]
