# Generated by Django 6.1 on 2026-08-24 15:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('portfolios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'في الانتظار'), ('processing', 'قيد التحليل'), ('completed', 'اكتمل التحليل'), ('failed', 'فشل التحليل')], db_index=True, default='pending', max_length=20, verbose_name='حالة التحليل')),
                ('summary', models.TextField(blank=True, verbose_name='ملخص العمل')),
                ('scientific_concepts', models.JSONField(blank=True, default=list, verbose_name='المفاهيم العلمية')),
                ('strengths', models.JSONField(blank=True, default=list, verbose_name='نقاط القوة')),
                ('improvement_areas', models.JSONField(blank=True, default=list, verbose_name='جوانب التحسين')),
                ('missing_requirements', models.JSONField(blank=True, default=list, verbose_name='المتطلبات الناقصة')),
                ('suggested_feedback', models.TextField(blank=True, verbose_name='التغذية الراجعة المقترحة')),
                ('suggested_score', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الدرجة المقترحة')),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='درجة الثقة')),
                ('provider_name', models.CharField(blank=True, max_length=100, verbose_name='مزود الذكاء الاصطناعي')),
                ('model_name', models.CharField(blank=True, max_length=100, verbose_name='اسم النموذج')),
                ('error_message', models.TextField(blank=True, verbose_name='رسالة الخطأ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ طلب التحليل')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ اكتمال التحليل')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_ai_analyses', to=settings.AUTH_USER_MODEL, verbose_name='طلب التحليل بواسطة')),
                ('submission_version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis', to='portfolios.submissionversion', verbose_name='نسخة العمل')),
            ],
            options={
                'verbose_name': 'تحليل ذكي',
                'verbose_name_plural': 'التحليلات الذكية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=100, verbose_name='الخاصية المستخدمة')),
                ('provider_name', models.CharField(blank=True, max_length=100, verbose_name='مزود الخدمة')),
                ('model_name', models.CharField(blank=True, max_length=100, verbose_name='اسم النموذج')),
                ('input_tokens', models.PositiveIntegerField(default=0, verbose_name='رموز الإدخال')),
                ('output_tokens', models.PositiveIntegerField(default=0, verbose_name='رموز الإخراج')),
                ('duration_ms', models.PositiveIntegerField(default=0, verbose_name='مدة التنفيذ بالمللي ثانية')),
                ('was_successful', models.BooleanField(default=True, verbose_name='تمت العملية بنجاح')),
                ('error_code', models.CharField(blank=True, max_length=100, verbose_name='رمز الخطأ')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الاستخدام')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usage_logs', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل استخدام ذكي',
                'verbose_name_plural': 'سجلات الاستخدام الذكي',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_activities', models.PositiveIntegerField(default=0, verbose_name='إجمالي الأنشطة')),
                ('submitted_activities', models.PositiveIntegerField(default=0, verbose_name='الأنشطة المسلمة')),
                ('approved_activities', models.PositiveIntegerField(default=0, verbose_name='الأنشطة المعتمدة')),
                ('late_activities', models.PositiveIntegerField(default=0, verbose_name='الأنشطة المتأخرة')),
                ('completion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='نسبة الإنجاز')),
                ('average_score', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='متوسط الدرجات')),
                ('risk_level', models.CharField(choices=[('low', 'مستقرة'), ('medium', 'تحتاج متابعة'), ('high', 'تحتاج تدخلًا')], db_index=True, default='low', max_length=20, verbose_name='مستوى الاحتياج للمتابعة')),
                ('insights', models.JSONField(blank=True, default=list, verbose_name='المؤشرات والاستنتاجات')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ إنشاء المؤشرات')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_snapshots', to='portfolios.portfolio', verbose_name='دفتر الطالبة')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_snapshots', to='academics.term', verbose_name='الفصل الدراسي')),
            ],
            options={
                'verbose_name': 'لقطة أداء',
                'verbose_name_plural': 'لقطات الأداء',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(choices=[('remedial', 'علاجية'), ('enrichment', 'إثرائية'), ('motivational', 'تحفيزية'), ('organizational', 'تنظيمية')], max_length=20, verbose_name='نوع التوصية')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان التوصية')),
                ('description', models.TextField(verbose_name='تفاصيل التوصية')),
                ('resource_url', models.URLField(blank=True, verbose_name='رابط المورد التعليمي')),
                ('priority', models.PositiveSmallIntegerField(default=1, verbose_name='الأولوية')),
                ('status', models.CharField(choices=[('new', 'جديدة'), ('shared', 'تمت مشاركتها'), ('completed', 'تم تنفيذها'), ('dismissed', 'تم استبعادها')], default='new', max_length=20, verbose_name='حالة التوصية')),
                ('created_by_ai', models.BooleanField(default=True, verbose_name='تم إنشاؤها بالذكاء الاصطناعي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='academics.lesson', verbose_name='الدرس')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='portfolios.portfolio', verbose_name='دفتر الطالبة')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_recommendations', to=settings.AUTH_USER_MODEL, verbose_name='راجعتها المعلمة')),
            ],
            options={
                'verbose_name': 'توصية',
                'verbose_name_plural': 'التوصيات',
                'ordering': ['priority', '-created_at'],
            },
        ),
    ]
