# Generated by Django 6.1 on 2026-08-26 05:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('intelligence', '0001_initial'),
        ('portfolios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyHonor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_start', models.DateField(unique=True, verbose_name='بداية الشهر')),
                ('month_end', models.DateField(verbose_name='نهاية الشهر')),
                ('hijri_month_label', models.CharField(help_text='مثال: ربيع الأول 1448هـ', max_length=100, verbose_name='اسم الشهر الهجري')),
                ('average_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='متوسط التقييم من 20')),
                ('completion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='نسبة إنجاز الأنشطة')),
                ('improvement_rate', models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)], verbose_name='نسبة التحسن')),
                ('submitted_activities', models.PositiveIntegerField(default=0, verbose_name='عدد الأنشطة المسلمة')),
                ('approved_activities', models.PositiveIntegerField(default=0, verbose_name='عدد الأعمال المعتمدة')),
                ('featured_activities', models.PositiveIntegerField(default=0, verbose_name='عدد الأعمال المتميزة')),
                ('selection_reason', models.TextField(verbose_name='سبب اختيار الطالبة')),
                ('ticker_message', models.CharField(blank=True, help_text='إذا تُركت فارغة سيُنشئ النظام عبارة افتراضية.', max_length=300, verbose_name='رسالة الشريط المتحرك')),
                ('publish_student_name', models.BooleanField(default=False, help_text='عند عدم التفعيل سيظهر: طالبة متميزة.', verbose_name='موافقة نشر الاسم الأول')),
                ('is_approved', models.BooleanField(db_index=True, default=False, verbose_name='معتمد')),
                ('is_active_in_ticker', models.BooleanField(db_index=True, default=False, verbose_name='ظاهر في الشريط المتحرك')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاعتماد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_monthly_honors', to=settings.AUTH_USER_MODEL, verbose_name='اعتمد بواسطة')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monthly_honors', to='academics.classroom', verbose_name='الفصل')),
                ('featured_submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_honor_records', to='portfolios.submission', verbose_name='أبرز عمل متميز')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.PROTECT, related_name='monthly_honors', to=settings.AUTH_USER_MODEL, verbose_name='الطالبة المكرمة')),
            ],
            options={
                'verbose_name': 'عالمة الشهر',
                'verbose_name_plural': 'عالمات الشهر',
                'ordering': ['-month_start'],
            },
        ),
    ]
