# Generated by Django 6.1 on 2026-08-24 15:02

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='البريد الإلكتروني')),
                ('role', models.CharField(choices=[('admin', 'مديرة النظام'), ('teacher', 'معلمة'), ('student', 'طالبة'), ('parent', 'ولي أمر')], db_index=True, default='student', max_length=20, verbose_name='نوع الحساب')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='رقم الجوال')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profiles/avatars/', verbose_name='الصورة الشخصية')),
                ('is_verified', models.BooleanField(default=False, verbose_name='الحساب موثّق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ إنشاء الحساب')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'مستخدم',
                'verbose_name_plural': 'المستخدمون',
                'ordering': ['first_name', 'last_name', 'username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='الرقم المدرسي')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد')),
                ('guardian_name', models.CharField(blank=True, max_length=150, verbose_name='اسم ولي الأمر')),
                ('guardian_phone', models.CharField(blank=True, max_length=20, verbose_name='رقم جوال ولي الأمر')),
                ('guardian_email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني لولي الأمر')),
                ('learning_preferences', models.JSONField(blank=True, default=dict, verbose_name='تفضيلات التعلم')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='الطالبة')),
            ],
            options={
                'verbose_name': 'ملف طالبة',
                'verbose_name_plural': 'ملفات الطالبات',
            },
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_number', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='الرقم الوظيفي')),
                ('specialization', models.CharField(blank=True, default='العلوم', max_length=100, verbose_name='التخصص')),
                ('qualification', models.CharField(blank=True, max_length=150, verbose_name='المؤهل العلمي')),
                ('bio', models.TextField(blank=True, verbose_name='نبذة تعريفية')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL, verbose_name='المعلمة')),
            ],
            options={
                'verbose_name': 'ملف معلمة',
                'verbose_name_plural': 'ملفات المعلمات',
            },
        ),
    ]
