# Generated by Django 6.1 on 2026-08-24 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='مثال: 1448هـ', max_length=30, unique=True, verbose_name='اسم العام الدراسي')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
                ('is_current', models.BooleanField(default=False, verbose_name='العام الحالي')),
            ],
            options={
                'verbose_name': 'عام دراسي',
                'verbose_name_plural': 'الأعوام الدراسية',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'مستمرة'), ('transferred', 'منقولة'), ('withdrawn', 'منسحبة'), ('completed', 'مكتملة')], default='active', max_length=20, verbose_name='حالة التسجيل')),
                ('joined_at', models.DateField(auto_now_add=True, verbose_name='تاريخ الانضمام')),
                ('left_at', models.DateField(blank=True, null=True, verbose_name='تاريخ المغادرة')),
            ],
            options={
                'verbose_name': 'تسجيل طالبة',
                'verbose_name_plural': 'تسجيلات الطالبات',
                'ordering': ['classroom', 'student__first_name'],
            },
        ),
        migrations.CreateModel(
            name='GradeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='اسم الصف')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='رمز الصف')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'صف دراسي',
                'verbose_name_plural': 'الصفوف الدراسية',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الدرس')),
                ('learning_objectives', models.TextField(blank=True, verbose_name='نواتج التعلم')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='ترتيب الدرس')),
                ('is_active', models.BooleanField(default=True, verbose_name='درس نشط')),
            ],
            options={
                'verbose_name': 'درس',
                'verbose_name_plural': 'الدروس',
                'ordering': ['unit', 'order'],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المدرسة')),
                ('education_department', models.CharField(blank=True, default='الإدارة العامة للتعليم بعسير', max_length=200, verbose_name='إدارة التعليم')),
                ('principal_name', models.CharField(blank=True, max_length=150, verbose_name='اسم مديرة المدرسة')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='schools/logos/', verbose_name='شعار المدرسة')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='العنوان')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم التواصل')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('is_active', models.BooleanField(default=True, verbose_name='مدرسة نشطة')),
            ],
            options={
                'verbose_name': 'مدرسة',
                'verbose_name_plural': 'المدارس',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='العلوم', max_length=100, verbose_name='اسم المقرر')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='رمز المقرر')),
                ('description', models.TextField(blank=True, verbose_name='وصف المقرر')),
                ('is_active', models.BooleanField(default=True, verbose_name='مقرر نشط')),
            ],
            options={
                'verbose_name': 'مقرر',
                'verbose_name_plural': 'المقررات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TeachingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='إسناد نشط')),
            ],
            options={
                'verbose_name': 'إسناد تدريس',
                'verbose_name_plural': 'إسنادات التدريس',
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(choices=[(1, 'الفصل الدراسي الأول'), (2, 'الفصل الدراسي الثاني'), (3, 'الفصل الدراسي الثالث')], verbose_name='الفصل الدراسي')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
                ('is_current', models.BooleanField(default=False, verbose_name='الفصل الحالي')),
            ],
            options={
                'verbose_name': 'فصل دراسي',
                'verbose_name_plural': 'الفصول الدراسية',
                'ordering': ['academic_year', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الوحدة')),
                ('description', models.TextField(blank=True, verbose_name='وصف الوحدة')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='ترتيب الوحدة')),
            ],
            options={
                'verbose_name': 'وحدة تعليمية',
                'verbose_name_plural': 'الوحدات التعليمية',
                'ordering': ['term', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='مثال: أ', max_length=30, verbose_name='اسم الشعبة')),
                ('is_active', models.BooleanField(default=True, verbose_name='شعبة نشطة')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='academics.academicyear', verbose_name='العام الدراسي')),
            ],
            options={
                'verbose_name': 'شعبة صفية',
                'verbose_name_plural': 'الشعب الصفية',
                'ordering': ['grade_level__order', 'name'],
            },
        ),
    ]
