# Generated by Django 6.1 on 2026-08-24 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='homeroom_teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeroom_classrooms', to=settings.AUTH_USER_MODEL, verbose_name='رائدة الفصل'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academics.classroom', verbose_name='الشعبة'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL, verbose_name='الطالبة'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='grade_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classrooms', to='academics.gradelevel', verbose_name='الصف'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='academics.school', verbose_name='المدرسة'),
        ),
        migrations.AddField(
            model_name='teachingassignment',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to='academics.classroom', verbose_name='الشعبة'),
        ),
        migrations.AddField(
            model_name='teachingassignment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to='academics.subject', verbose_name='المقرر'),
        ),
        migrations.AddField(
            model_name='teachingassignment',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to=settings.AUTH_USER_MODEL, verbose_name='المعلمة'),
        ),
        migrations.AddField(
            model_name='term',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='academics.academicyear', verbose_name='العام الدراسي'),
        ),
        migrations.AddField(
            model_name='unit',
            name='grade_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='academics.gradelevel', verbose_name='الصف'),
        ),
        migrations.AddField(
            model_name='unit',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='academics.subject', verbose_name='المقرر'),
        ),
        migrations.AddField(
            model_name='unit',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='academics.term', verbose_name='الفصل الدراسي'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='academics.unit', verbose_name='الوحدة'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('student', 'classroom'), name='unique_student_enrollment'),
        ),
        migrations.AddConstraint(
            model_name='classroom',
            constraint=models.UniqueConstraint(fields=('school', 'academic_year', 'grade_level', 'name'), name='unique_classroom_per_year'),
        ),
        migrations.AddConstraint(
            model_name='teachingassignment',
            constraint=models.UniqueConstraint(fields=('teacher', 'classroom', 'subject'), name='unique_teaching_assignment'),
        ),
        migrations.AddConstraint(
            model_name='term',
            constraint=models.UniqueConstraint(fields=('academic_year', 'number'), name='unique_term_per_academic_year'),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(fields=('subject', 'grade_level', 'term', 'order'), name='unique_unit_order'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('unit', 'order'), name='unique_lesson_order_per_unit'),
        ),
    ]
